### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by bouaafia23** [ishfaq06/Deep-Q-Learning-based-Downlink-Power-Allocation#1]
Hi Sir, 
I am interesting to reproduce your code, but I got this error. (OSError: Unable to open file (unable to open file: name = 'dqn_5c_3h_5p.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0).
Could you tell me how can I solve it?

Sincerely.

**Comment by ishfaq06** [comment]
Hello,

Thank you for the feedback. I have corrected the errors. There are errors because the files do not exist at the first time. Make those lines as comments and the code will work.

**Comment by bouaafia23** [comment]
Thanks a lots for your reply, 
Could you  send me these file(counter_v2_5c_3h_5p_lr1.npy  , data_set_5c.npz)? mentioned in your code?
My email address is: bouaafia1992@gmail.com.
Many thanks in advance.

**Comment by bouaafia23** [comment]
Thanks a lots for your reply,
Could you send me these file(counter_v2_5c_3h_5p_lr1.npy ,
data_set_5c.npz)? mentioned in your code?
My email address is: bouaafia1992@gmail.com.
Many thanks in advance.
