### ISSUE TITLE
dql_main steps

### ISSUE THREAD

**Issue by bouaafia23** [ishfaq06/Deep-Q-Learning-based-Downlink-Power-Allocation#2]
I need to know if these steps are normal or not? because the code (dql_main.py) has been looping since 15 days like the screenshot below?

![image](https://user-images.githubusercontent.com/45732399/76342612-2975f400-62ff-11ea-8e6d-1a50dbfab177.png)

**Comment by ishfaq06** [comment]
Sorry I am very busy..yes it will run forever. For comparison purpose you
need to save some samples and need to calculate the optimal solutions for
those samples. Then you can compare.
