### ISSUE TITLE
Some troubles

### ISSUE THREAD

**Issue by XuLuyap** [ishfaq06/Deep-Q-Learning-based-Downlink-Power-Allocation#3]
Hello, I have some doubts about your code, the data_set dataset in it seems to be undefined, can you upload the dataset you use?

**Comment by sanabel99** [comment]
![Uploading B457A520-22ED-4B65-B224-4AA0C9518500.jpeg…]()
Did you slove it?

**Comment by sanabel99** [comment]
Did you slove it?

**Comment by ishfaq06** [comment]
Sorry, It was long time ago. I can not recall what I have done. Probably, you need to run this one first (python data_generator.py) to generate a few data points and then you can run the main file.

**Comment by sanabel99** [comment]
Dear,

Please try to compress dataset file and send it to me.
