### ISSUE TITLE
name ‘data_set ‘ is not defined 

### ISSUE THREAD

**Issue by sanabel99** [ishfaq06/Deep-Q-Learning-based-Downlink-Power-Allocation#4]
![8D6E2AE8-6926-4CB3-9794-93A92B0CEE50](https://user-images.githubusercontent.com/89363372/209966474-1c437a51-c323-4240-a46b-99ddea97af5b.jpeg)
I run the code, i got this issue . How i can slove this?

**Comment by ishfaq06** [comment]
Hi Sanabel,

Sorry, It was long time ago. I can not recall what I have done. Probably, you need to run this one first (python data_generator.py) to generate  a few data points and then you can run the main file. Also, probably you need to comment out line 1742 to load the data set for the first time when you are running. I am not sure. Sorry, I could not help. Data set was huge, so, I was not able to upload it at that time.

Hope it will help. Thanks.

Kazi

**Comment by sanabel99** [comment]
> Hi Sanabel,
> 
> Sorry, It was long time ago. I can not recall what I have done. Probably, you need to run this one first (python data_generator.py) to generate a few data points and then you can run the main file. Also, probably you need to comment out line 1742 to load the data set for the first time when you are running. I am not sure. Sorry, I could not help. Data set was huge, so, I was not able to upload it at that time.
> 
> Hope it will help. Thanks.
> 
> Kazi

In READ ME you said, Generation files used for testing and compartion!  Are you sure about what I should run first?  
Also, I would like to ask what did you use for training cpu or gpu? What’s its specifications? How many time it will take?

Thanks for your help

**Comment by sanabel99** [comment]
Dear,


Please, try to compress your dataset file and send it to me by email. I
really I need this help.

Thank you  very much.
